# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ali Akbar Mehta
email: aliakbarmehta@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ali Akbar Mehta is a Trans-media artist. He is a founder-member and current Artistic Director of Museum of Impossible Forms, Helsinki.

  Through his research-based transmedia practice, he creates immersive cyber archives that explore collective memetic history, narratives of memory, identity, violence, and conflict. He has exhibited his projects in galleries and alternate spaces in New Delhi, Mumbai, Pune, Helsinki, and Tampere. He holds a BFA in Drawing and Painting from Sir J.J. School of Art, Mumbai, and an MA in Visual Culture, Curating, and Contemporary Art from Aalto University, Helsinki, Finland, where he completed a thesis text titled ‘Cyber Archive: Being and Doing Knowledge’.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

social:
  email: aliakbarmehta@gmail.com
  facebook: https://www.facebook.com/aliakbarmehta
  instagram: https://www.instagram.com/@aliakbarmehta/
  linkedin: https://www.linkedin.com/in/ali-akbar-mehta-91511aa/
  vimeo: https://vimeo.com/aliakbarmehta
  facebook: https://www.facebook.com/studioaliakbarmehta

# Collections
collections:
  pages:
    output: true
  content:
    output: true

# Build settings
markdown: kramdown
include:
  - _pages
  - _content
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
