backend:
  name: git-gateway
  branch: move-to-11ty # Branch to update (master by default)
  site_domain: https://dev-aam.netlify.com/

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "static/img"

collections: # A list of collections the CMS should be able to edit
  - name: "page" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Page" # Used in the UI, ie.: "New Post"
    folder: "pages" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "page"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Permalink"
        name: "permalink"
        required: true
        widget: "string"
      - label: "Body"
        name: "body"
        required: false
        widget: "markdown"
  - name: "content" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Content" # Used in the UI, ie.: "New Post"
    folder: "content" # The path to the folder where the documents are stored
    sort: "title:asc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    fields: # The fields each document in this collection have
      - label: "Title"
        name: "title"
        required: false
        widget: "string"
      - label: "Subtitle"
        name: "subtitle"
        required: false
        widget: "string"
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: content
      - label: "Tags"
        name: "tags"
        widget: "select"
        options: ["ongoing project","past project","curatorial project","artwork","group exhibition","solo exhibition","performance","press","publication","unpublished","residency","resource","artist talk","teaching","text","video"]
      - label: "Date"
        name: "pubdate"
        widget: "date"
        format: "YYYY"
      - label: "Hero Image"
        name: "hero"
        required: false
        widget: "image"
      - label: "Summary"
        name: "summary"
        required: false
        widget: "markdown"
      - label: "Body"
        name: "body"
        required: false
        widget: "markdown"
      - label: "Parent"
        name: "parent"
        required: false
        widget: "relation"
        collection: "content"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
      - label: "Children"
        name: "children"
        required: false
        widget: "list"
        field: {label: "Content", name: "children", widget: "relation", collection: "content", searchFields: ["title"], valueField: "title", displayFields: ["title"]}
