backend:
  name: git-gateway
  branch: master # Branch to update (master by default)
  site_domain: https://aliakbarmehta.netlify.com/

media_folder: "assets/img" # Folder where user uploaded files should go
public_folder: "_site/assets/img"

collections: # A list of collections the CMS should be able to edit
  - name: "page" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Page" # Used in the UI, ie.: "New Post"
    folder: "_pages" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "page"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Permalink"
        name: "permalink"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
  - name: "peoject" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Project" # Used in the UI, ie.: "New Post"
    folder: "_projects" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "project"
      - label: "Title"
        name: "title"
        required: false
        widget: "string"
      - label: "Hero Image"
        name: "hero"
        required: false
        widget: "image"
      - label: "Progression"
        name: "progression"
        required: false
        widget: "list"
        fields:
        - {label: Year, name: year, widget: string}
        - {label: Genre, name: genre, widget: string}
      - label: "Body"
        name: "body"
        widget: "markdown"
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
  - name: "content" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Project Content" # Used in the UI, ie.: "New Post"
    folder: "_content" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - label: "Title"
        name: "title"
        required: false
        widget: "string"
      - label: "Parent Project"
        name: "project"
        widget: "relation"
        collection: "_projects"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
      - label: "Content Type"
        name: "layout"
        widget: "select"
        options: ["text","publications","videos","artwork","exhibitions","talks","press","resources"]
      - label: "Date"
        name: "pubdate"
        widget: "date"
        format: "YYYY"
      - label: "Body"
        name: "body"
        widget: "markdown"
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
